/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projet_mappage;

/**
 *
 * @author user
 */
public class Connecter extends javax.swing.JPanel {
private String email,password;
    /**
     * Creates new form Home
     * 1097 604
     */
    public Connecter() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        id_inscrire = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        id_password = new javax.swing.JPasswordField();
        id_email = new javax.swing.JTextField();
        id_checkbox = new javax.swing.JCheckBox();
        id_connecter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 147));
        setBorder(new javax.swing.border.MatteBorder(null));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(6, 183, 182));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Test les performances ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 392, 270, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 610));

        id_inscrire.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        id_inscrire.setForeground(new java.awt.Color(204, 204, 204));
        id_inscrire.setText("s'inscrire");
        add(id_inscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 480, 140, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("se connecter ou s'inscrire ");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 120, 250, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 255, 255));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 420, 10));

        jSeparator3.setBackground(new java.awt.Color(204, 255, 255));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 510, 110, 10));

        id_password.setBackground(new java.awt.Color(0, 0, 147));
        id_password.setForeground(new java.awt.Color(255, 255, 255));
        id_password.setText("jPasswordField1");
        id_password.setBorder(null);
        id_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_passwordActionPerformed(evt);
            }
        });
        add(id_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 420, 30));

        id_email.setBackground(new java.awt.Color(0, 0, 147));
        id_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_email.setForeground(new java.awt.Color(255, 255, 255));
        id_email.setText("Enter votre email");
        id_email.setToolTipText("");
        id_email.setBorder(null);
        id_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_emailActionPerformed(evt);
            }
        });
        add(id_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 420, 30));

        id_checkbox.setBackground(new java.awt.Color(0, 0, 147));
        id_checkbox.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        id_checkbox.setForeground(new java.awt.Color(255, 255, 255));
        id_checkbox.setSelected(true);
        id_checkbox.setText("Enregistre");
        id_checkbox.setToolTipText("");
        id_checkbox.setBorder(null);
        add(id_checkbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, -1, -1));

        id_connecter.setBackground(new java.awt.Color(6, 183, 182));
        id_connecter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Connecter");
        id_connecter.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        add(id_connecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 480, 130, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Email");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 130, 30));

        jSeparator4.setBackground(new java.awt.Color(204, 255, 255));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 350, 420, 10));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Mots de passe");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void id_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_passwordActionPerformed

    private void id_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_emailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox id_checkbox;
    private javax.swing.JPanel id_connecter;
    private javax.swing.JTextField id_email;
    private javax.swing.JLabel id_inscrire;
    private javax.swing.JPasswordField id_password;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
