/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.projet_mappage;

/**
 *
 * @author user
 */
public class Inscription extends javax.swing.JPanel {

    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        id_inscrire = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        id_password = new javax.swing.JPasswordField();
        id_email = new javax.swing.JTextField();
        id_connecter = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        id_email1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        id_email2 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 147));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(6, 183, 182));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Test les performances ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 220, -1));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 392, 270, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 630));

        id_inscrire.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        id_inscrire.setForeground(new java.awt.Color(204, 204, 204));
        id_inscrire.setText("retour la page login");
        jPanel1.add(id_inscrire, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 540, 140, 30));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("se connecter ou s'inscrire ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 250, -1));

        jSeparator1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 250, 420, 10));

        jSeparator3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 140, 10));

        id_password.setBackground(new java.awt.Color(0, 0, 147));
        id_password.setForeground(new java.awt.Color(255, 255, 255));
        id_password.setText("jPasswordField1");
        id_password.setBorder(null);
        id_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_passwordActionPerformed(evt);
            }
        });
        jPanel1.add(id_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 460, 420, 30));

        id_email.setBackground(new java.awt.Color(0, 0, 147));
        id_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_email.setForeground(new java.awt.Color(255, 255, 255));
        id_email.setText("Enter votre numero telephone");
        id_email.setToolTipText("");
        id_email.setBorder(null);
        id_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_emailActionPerformed(evt);
            }
        });
        jPanel1.add(id_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 420, 30));

        id_connecter.setBackground(new java.awt.Color(6, 183, 182));
        id_connecter.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("S'inscrire");
        id_connecter.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 20));

        jPanel1.add(id_connecter, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 540, 130, 40));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("telephone");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 130, 30));

        jSeparator4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 420, 10));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Mots de passe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 420, 140, 30));

        jSeparator5.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 420, 10));

        id_email1.setBackground(new java.awt.Color(0, 0, 147));
        id_email1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_email1.setForeground(new java.awt.Color(255, 255, 255));
        id_email1.setText("Enter votre nom utilisateur ");
        id_email1.setToolTipText("");
        id_email1.setBorder(null);
        jPanel1.add(id_email1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 420, 30));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("Nom utilisateur");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 60, 140, 30));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Email");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 320, 130, 30));

        id_email2.setBackground(new java.awt.Color(0, 0, 147));
        id_email2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        id_email2.setForeground(new java.awt.Color(255, 255, 255));
        id_email2.setText("Enter votre email");
        id_email2.setToolTipText("");
        id_email2.setBorder(null);
        id_email2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_email2ActionPerformed(evt);
            }
        });
        jPanel1.add(id_email2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 360, 420, 30));

        jSeparator6.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, 420, 10));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1100, 640));
    }// </editor-fold>//GEN-END:initComponents

    private void id_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_passwordActionPerformed

    private void id_email2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_email2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_email2ActionPerformed

    private void id_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_emailActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel id_connecter;
    private javax.swing.JTextField id_email;
    private javax.swing.JTextField id_email1;
    private javax.swing.JTextField id_email2;
    private javax.swing.JLabel id_inscrire;
    private javax.swing.JPasswordField id_password;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
